name: 'Release package - v1'
on:
  workflow_dispatch:
    inputs:
      version-new:
        description: 'Ex: 1.3.5'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_TOKEN }}
      
      - name: Setup Git
        run: |
          git config --global user.email "ramiro@cgcontadores.com.br"
          git config --global user.name "ramirooliveiracg"

      - name: Retrieve version
        run: |
          echo "version_old=$(grep -Po '[0-9]\.[0-9]\.[0-9]' package.json | head -1)" >> $GITHUB_OUTPUT
        id: version

      - name: Change version package
        run: |
          sed -i '0,/${{ steps.version.outputs.version_old }}/{s/${{ steps.version.outputs.version_old }}/${{ github.event.inputs.version-new }}/}' package.json
          sed -i '0,/${{ steps.version.outputs.version_old }}/{s/${{ steps.version.outputs.version_old }}/${{ github.event.inputs.version-new }}/}' package-lock.json
          sed -i '0,/${{ steps.version.outputs.version_old }}/{s/${{ steps.version.outputs.version_old }}/${{ github.event.inputs.version-new }}/}' package-lock.json

      - name: Fetch
        run: |
          git fetch --prune
          
      - name: Arquivo de Log
        run: |
          git --no-pager log --pretty=format:'%n{%n %x22commit%x22: %x22%H%x22,%n %x22author%x22: %x22%an%x22,%n %x22author_email%x22: %x22%ae%x22,%n %x22date%x22: %x22%ad%x22,%n %x22message%x22: %x22%f%x22%n},' > logs/changelog-data.json
          
      - name: Commit para atualizar os arquivos
        run: |
          git add .
          git commit -m "feat: ${{ steps.version.outputs.version_old }} - ${{ github.event.inputs.version-new }}"

      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git push

      # Cria a nova tag release
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.version-new }}
          release_name: ${{ github.event.inputs.version-new }}
          body: |
            Conteúdo disponível no arquivo "logs/changelog-data.json"
          draft: false
          prerelease: false
